import type { Metadata } from 'next'
import { AppBar, Box, Grid, Toolbar, Typography } from '@mui/material'
import '@/styles/styles.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body style={{margin: '0'}} >
      <Box sx={{width: '100%'}} >
            <AppBar style={{ backgroundColor: '#0A233F' }} position="static">
              <Toolbar>
                <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                  <span className='globalFont' style={{ fontWeight: 400, fontSize: '18px' }}>UNITED</span> <span className='globalFont' style={{ fontWeight: 400, fontSize: '18px' }}>CAPITAL | </span>
                  <span className='globalFont' style={{ fontWeight: 300, fontSize: '18px' }}>HAZTE</span> <span className='globalFont'  style={{ fontWeight: 300, fontSize: '18px' }}>CLIENTE</span>
                </Typography>
              </Toolbar>              
            </AppBar>
          </Box>   
     
          {children}
      </body>
    
    </html>
  )
}
